Traceback (most recent call last):
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furui/.local/share/uv/python/cpython-3.11.5-macos-aarch64-none/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/furui/Documents/class/zeropro/zero-pro2024-reccurent-public/.venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
import numpy as np
import matplotlib
import pandas as pd
import sklearn

# Python„ÅÆ„Éê„Éº„Ç∏„Éß„É≥„ÇíÂá∫Âäõ
print(f"Python Version: {sys.version}")

# ÂêÑ„É©„Ç§„Éñ„É©„É™„ÅÆ„Éê„Éº„Ç∏„Éß„É≥„ÇíÂá∫Âäõ
print(f"NumPy Version: {np.__version__}")
print(f"Matplotlib Version: {matplotlib.__version__}")
print(f"Pandas Version: {pd.__version__}")
print(f"Scikit-Learn Version: {sklearn.__version__}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01msklearn[39;00m
[1;32m      7[0m [38;5;66;03m# Python„ÅÆ„Éê„Éº„Ç∏„Éß„É≥„ÇíÂá∫Âäõ[39;00m
[1;32m      8[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mPython Version: [39m[38;5;132;01m{[39;00msys[38;5;241m.[39mversion[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'sklearn'

